# Idempotentency for relevant files in main
name: Remove lines
on:
  push:
    branches:
      - main
      - update
    paths:
      - 'pre-init.el'
      - 'init.el'
      - '.gitignore'
  pull_request:
    branches:
      - main
      - update
    paths:
      - 'pre-init.el'
      - 'init.el'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # The token is required to push changes back to the repository
          token: ${{ secrets.CI }} 

      - name: Remove lines
        # The 'run' keyword executes shell commands
        run: |
          # Define a shell variable for clarity
          SERVICE_VERSION=$(git rev-parse --short HEAD)

          # Download stable version 1.42
          curl --output early-init.el "https://raw.githubusercontent.com/jamescherti/minimal-emacs.d/0d07164f86e396884d7b3562abb94ce1b93d2f8f/early-init.el"
          curl --output init.el "https://raw.githubusercontent.com/jamescherti/minimal-emacs.d/0d07164f86e396884d7b3562abb94ce1b93d2f8f/init.el"
          
          # Use sed to replace the placeholder
          # -i flag for inline editing
          # 's|...|...|g' is the substitution syntax. We use '|' as delimiter to avoid escaping '/' in URLs/paths
          # Note: The -i flag's behavior can differ slightly between GNU sed (Linux) and BSD sed (macOS).
          # On Linux, `sed -i` works. On macOS, you might need `sed -i ''`. Ubuntu runners are Linux.
          
          # 2,21d: initial comment block after lexical-binding to ';;; Code:'
          # 98,109d: disable vars that check for other user files
          # 129,130d: disable check for home directory emacs configs
          # 160,161d: minimal-emacs-load-user-init invoked
          # 485,486d: minimal-emacs-load-user-init invoked
          sed -i "1,21d;98,109d;129,130d;160,161d;485,486d" early-init.el
          
          # 1,22d: Initial comment block including lexical binding up to ';;; Code:'
          # 26,29d: minimal-emacs-load-user-init invoked
          # 566,568d: minimal-emacs-load-user-init invoked
          sed -i "1,22d;26,29d;566,568d" init.el

          # Make gitignore idempotent
          echo -e "# Source - https://stackoverflow.com/a/987162\n\n# Posted by Joakim Elofsson, modified by community. See post 'Timeline' for change history\n\n# Retrieved 2026-03-09, License - CC BY-SA 3.0\n\n# Ignore everything\n*\n\n# Lock files\ndevenv.lock\n\n# Even the hidden things\n.devenv/*\n.direnv/*\n\n# Lock files\ndevenv.lock\n\n# But not these files...\n\!.gitignore\n\!config.org\n# etc...\n\n# ...even if they are in subdirectories\n\!*/\n" | tee .gitignore 
         
      - name: Add, commit, and push
        # You may pin to the exact commit or the version.
        # uses: actions4git/add-commit-push@2119cc12fc9e451198b0d1c27fbae6fd1b134135
        uses: actions4git/add-commit-push@v1.0.0
